/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacevendas;
import beans.Cliente;
import dao.ClienteDAO;
import dao.ProdutoDAO;
import javax.swing.JOptionPane;
/**
 *
 * @author Tonho
 */
public class FormCadCliente extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceCadastro
     */
    public FormCadCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSenhaCliente = new javax.swing.JTextField();
        btnCliente = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtConfSenha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 300));
        setMinimumSize(new java.awt.Dimension(400, 270));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(99, 51, 52, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Cadastro de Cliente");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(121, 11, 153, 22);
        getContentPane().add(txtNomeCliente);
        txtNomeCliente.setBounds(155, 55, 119, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Senha:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(99, 86, 54, 22);
        getContentPane().add(txtSenhaCliente);
        txtSenhaCliente.setBounds(157, 90, 117, 20);

        btnCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCliente.setText("Confirmar");
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnCliente);
        btnCliente.setBounds(148, 184, 109, 31);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Confirme a Senha:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 121, 146, 22);
        getContentPane().add(txtConfSenha);
        txtConfSenha.setBounds(160, 125, 114, 20);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(350, 70, 50, 40);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        if(txtNomeCliente.getText().isEmpty() || txtSenhaCliente.getText().isEmpty() || txtConfSenha.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Preencha todos os campos");
            return;
        }
        if(txtSenhaCliente.getText().compareTo(txtConfSenha.getText()) != 0){
            JOptionPane.showMessageDialog(rootPane, "Sehnas diferentes");
            return;            
        }
        JOptionPane.showConfirmDialog(this, ("Confirmar todas as informações?"));
        String nomeCliente = txtNomeCliente.getText();
        String senhaCliente = txtSenhaCliente.getText(); 
        
        
        ClienteDAO clienteDAO = new ClienteDAO();
        
        clienteDAO.inserir(nomeCliente, senhaCliente);
        txtNomeCliente.setText("");
        txtSenhaCliente.setText("");
        txtConfSenha.setText("");
        
    }//GEN-LAST:event_btnClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCadCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCadCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtConfSenha;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtSenhaCliente;
    // End of variables declaration//GEN-END:variables
}
